### PR TITLE
add footer to the page

### PR DESCRIPTION
**Pull request by erizocosmico**

### CODE REVIEW

**Comment by Serabe** [comment]
For me is approved, but I would like to have @marnovo's approval before merging.

**Comment by erizocosmico** [comment]
Oopsie, forgot the screenshot.
On Thu, 6 Jul 2017 at 16:51, Sergio Arbeo <notifications@github.com<mailto:notifications@github.com>> wrote:

@Serabe approved this pull request.

**Comment by Serabe** [comment]
@erizocosmico don't worry. I always do too.

**Comment by marnovo** [comment]
Yep, that's like it. 👍 

As last moment feedback, would you guys change "coded by" to "built by" or any other word? How does it sound better? @Serabe @erizocosmico

**Comment by Serabe** [comment]
In any case, my suggestion should be taken as a change of scope and be addressed on a different PR.

**Comment by marnovo** [comment]
@Serabe agreed. Approved, then (I can't formally approve in this org/repo…).

**Pull request merged**
