### PR TITLE
add csscomb and editorconfig

### PR DESCRIPTION
**Pull request by erizocosmico**
This already contains the hook from platform-starter.

### CODE REVIEW

**Comment by dpordomingo** [comment]
@erizocosmico you said that this PR:
>_already contains the hook from platform-starter._
I did not found it. Did you missed it? Or did you meant to say that you already ran the linters and fixers for the project?

**Comment by erizocosmico** [comment]
No, I meant it has them. The hooks are not visible in the commit AFAIK, they are added to the `.git`.

**Comment by Serabe** [comment]
Hooks are not committed at all. Ever.

**Comment by Serabe** [comment]
If you want, something like [husky](https://www.npmjs.com/package/husky) can be used for sharing hooks

**Comment by erizocosmico** [comment]
Damn, thought the hooks were magically uploaded to the repo. Which, now that I think about it, makes no sense at all.

**Pull request merged**
