### PR TITLE
api: Upgrade to make it compatible with SDK v1.1

### PR DESCRIPTION
**Pull request by abeaumont**
Signed-off-by: Alfredo Beaumont <alfredo.beaumont@gmail.com>

This update is required to make it compatible with SDK `v1.1`.
The server should be running at least `v1.1.1` to work with this change and new drivers.

### CODE REVIEW

**Comment by dpordomingo** [comment]
Travis failed. Test do not pass.
Testing and fixing it locally.
It will be needed to update the `bidata` stuff as well

**Comment by dpordomingo** [comment]
Testing and fixing it locally.

**Comment by abeaumont** [comment]
@dpordomingo it fails in a react test.... I fail to see how it relates to this PR, any hint?

**Comment by abeaumont** [comment]
Oh, I did see it incorrectly. I can fix it.

**Comment by dpordomingo** [comment]
I did it
https://github.com/abeaumont/dashboard/pull/1

**Comment by dpordomingo** [comment]
But I'm still trying to run it locally.
Did you managed to get it running?

**Comment by abeaumont** [comment]
@dpordomingo ok, great!
Yes, I managed to get it working. You need an uptodate version of the server to make it work.
Note that the server has been renamed to `bblfshd` now, maybe that's causing the problem?
If you're using docker instead, make sure that you're working with the last version.

**Comment by dpordomingo** [comment]
The `bindata` stuff was done by https://github.com/abeaumont/dashboard/pull/2

**Pull request merged**
