### PR TITLE
Prepare README.md with useful commands

### PR DESCRIPTION
**Pull request by dpordomingo**
Useful for people using the tool, and not knowing a lot about its dependencies

Signed-off-by: David Pordomingo <David.Pordomingo.F@gmail.com>

### CODE REVIEW

**Comment by erizocosmico** [comment]
Why do we need this instead of, `yarn start` and `yarn test`?

**Comment by dpordomingo** [comment]
I just followed the guide of `create-react-app` which uses `npm run whatever`
We could merge this, and resume the `yarn` thing as an improvement in another PR

**Comment by erizocosmico** [comment]
I'd still prefer having it in the README (all the create-react-app readme mumbo jumbo can go away) instead of adding the requirement of using make.

**Comment by dpordomingo** [comment]
Are we not needing `Make` for Dashboard at all at any point of its development?
The benefit of using `make` is that it seems to be a  *de facto* standard in our repos, and a good entry point for people visiting them.

I'll update the `npm` commands to use the `yarn` alternatives, and wait for your confirmation @erizocosmico @Serabe about `Make`

**Comment by dpordomingo** [comment]
@erizocosmico `README.md` updated using yarn and `Make` deleted

**Comment by dpordomingo** [comment]
ping @erizocosmico @Serabe

**Comment by dpordomingo** [comment]
In case @Serabe approves it, I'll rebase against master to remove the dependency :D

**Pull request merged**
