### PR TITLE
Feature/xpath

### PR DESCRIPTION
**Pull request by smacker**
Based on https://github.com/bblfsh/dashboard/pull/76

Screenshots:
screen shot 2017-12-08 at 7 12 32 pm

screen shot 2017-12-08 at 7 12 46 pm

screen shot 2017-12-08 at 7 23 37 pm

### CODE REVIEW

**Comment by bzz** [comment]
Looks awesome, thank you for screenshots!

Let me try it later today and get back to you.

**Comment by bzz** [comment]
Did not have a chance to do it today, will take a look tomorrow.

**Comment by bzz** [comment]
Local `make serve` (which presumably is a test plan for this) fails for me with:

```
 make serve
make -C . assets SERVER_URL=http://0.0.0.0:9999/api
go get -v -t github.com/jteeuwen/go-bindata/...
go get -v -t github.com/bblfsh/dashboard/server
gopkg.in/bblfsh/client-go.v2/tools
# gopkg.in/bblfsh/client-go.v2/tools
In file included from ../../../gopkg.in/bblfsh/client-go.v2/tools/filter.go:14:
./bindings.h:8:10: fatal error: 'uast.h' file not found
#include "uast.h"
         ^~~~~~~~
1 error generated.
make[1]: *** [github.com/bblfsh/dashboard/server] Error 2
make: *** [serve] Error 2
```

**Comment by smacker** [comment]
It's due to strange installation process of client-go. I'll try to fix Makefile (not sure how to test though).

**Comment by smacker** [comment]
Yeah! fixed.

**Comment by bzz** [comment]
Thanks for prompt fix! I will give it another try first thing tomorrow.

**Comment by bzz** [comment]
👍 As mentioned before, please give me some time to try it out

**Comment by bzz** [comment]
I believe it's not related to XPath in particular, built `make serve` complains

```
The project was built assuming it is hosted at the server root.
To override this, specify the homepage in your package.json.
For example, add this to build it for GitHub Pages:

  "homepage" : "http://myname.github.io/myapp",

The build folder is ready to be deployed.
You may serve it with a static server:

  yarn global add serve
  serve -s build
```

Looks like it can be safely ignored, but I wonder if that is something reasonable beeing suggested in this warning.

**Comment by bzz** [comment]
Quick question - XPath query works like a charm, but how hard would it be to add default search result highlighting behaviour, similar Ctrl+F experience in browser, when all occurrences of the term are highlighted?

screen shot 2017-12-14 at 12 15 33 pm

Ofcourse we have different behaviour on hovering over uAST, and it's nice to keep it, so full highlight is dropped and only the hovered node is highlighted. To get full highlight back user would just need to click "Search" button again.

What do you think @smacker ?

**Comment by smacker** [comment]
shouldn't complicated. But it may cause behavior which looks like a bug:
I search, everything is highlighted. Then I move cursor to source code, to scroll down or whatever, it's very easy to hover node during this movement. And highlighting will disappear.

I'll implement that if you want. But maybe we should do it in separate PR? Then we can try it for real and decide should we merge it or not.

**Comment by bzz** [comment]
Totally agree. Let's keep further product improvement discussion out of this PR

**Comment by smacker** [comment]
thanks! I'm merging as soon as CI is green then!

**Comment by smacker** [comment]
oh. and that warning is from react-create-app. It's not really a warning, more a help message. I'll take a look how to remove it.

**Pull request merged**
