### PR TITLE
Clarify the readme and update with last SDK requirements

### PR DESCRIPTION
**Pull request by dpordomingo**
I updated the README.md with the latest requirements of the current SDK (as you saw, now it's needed to manually install the drivers)
I also used variables trying to show what parts of the commands are up to the user; I'm not sure if this would help. :question:

### CODE REVIEW

**Comment by smacker** [comment]
@campoy please review when you have time.

**Comment by smacker** [comment]
Okay. My thoughts:

1) It's really nice to show what you can configure. I would love to see it in README
2) I don't like that we put information about how to run server here too. It will get outdated one day for sure. I would prefer to have a link to server repo

**Comment by dpordomingo** [comment]
This enhancement was superseded by https://github.com/bblfsh/dashboard/issues/41 and https://github.com/bblfsh/dashboard/issues/37 as requested by https://github.com/src-d/backlog/issues/1074 so we can close this PR, and consider the better way to explain how to run the dashboard.

**addendum:** I agree with @smacker about his concern of explaining in the dashboard/README.md how to run the server, instead of linking the server/README.md

**Comment by mcuadros** [comment]
Copy pasting the installation instructions over and over a cross diferent repositories makes harded to mantain the project. Should be removed as has been removed from other repositories. 

We shouldn't point to the server readme, we should point to https://doc.bblf.sh/user/getting-started.html

**Pull request closed without merging**
